name: Create release

on:
  workflow_call:
    secrets:
      repo-token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux server archives
        uses: actions/download-artifact@v4
        with:
          pattern: albyhub-Server-Linux-*

      - name: Download desktop archives
        uses: actions/download-artifact@v4
        with:
          pattern: albyhub-Desktop-*

      - name: Create release without tag
        if: github.ref_type != 'tag'
        env:
          GH_TOKEN: ${{ secrets.repo-token }}
          tag: ${{ github.sha }}
        run: |
          echo "Release without tag not supported"
          exit 1

      - name: Create release with tag
        if: github.ref_type == 'tag'
        env:
          GH_TOKEN: ${{ secrets.repo-token }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create ${{ env.tag }}             \
            --repo="$GITHUB_REPOSITORY"                \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes                           \
            --draft                                    \
            --verify-tag                               \
            ./artifacts/*
