name: Docker build & push
on:
  push:
  release:
    types: [published]
jobs:
  build:
    env:
      REGISTRY: ghcr.io
      IMAGENAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run:  go test
    - name: Docker build
      uses: mr-smithers-excellent/docker-build-push@v6
      id: build
      with:
        image: ${{ env.IMAGENAME }}
        registry: ${{ env.REGISTRY }}
        multiPlatform: true
        platform: linux/amd64,linux/arm64,linux/386
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
